### ISSUE TITLE
Run makefs+upload from command line

### ISSUE THREAD

**Issue by hattesen** [earlephilhower/arduino-pico-littlefs-plugin#10]
Any chance mklittlefs+upload could be made to run from the command line, to make it possible for those of us that are not using the Arduino IDE to also upload files?

I realize that it would require setting FLASH addresses and source folder manually in the CLI arguments, but that should not be a bug problem, I think.

**Comment by earlephilhower** [comment]
That's exactly how the uploader works.  It uses this CLI tool: https://github.com/earlephilhower/mklittlefs

You can script it yourself in your own workflow.
