### ISSUE TITLE
tools not working with Arduino IDE 2.x

### ISSUE THREAD

**Issue by TheLardos** [earlephilhower/arduino-pico-littlefs-plugin#11]
Hi,

If anybody else is struggling to get ad-on tools like the littlefs plugin to work: You have to use the old Arduino IDE 1.8.x since the java based tools apparently don't work with the new IDE.

Hope this gets fixed in the future.

Cheers,
Luca

**Comment by earlephilhower** [comment]
The readme.md file explains what to do for 2.x.
