### ISSUE TITLE
Arduino IDE 2.0 compatible?

### ISSUE THREAD

**Issue by okyeron** [earlephilhower/arduino-pico-littlefs-plugin#3]
Should I expect this plugin to work in Arduino IDE 2.0?

Menu item does not appear in Arduino IDE 2.0.3

**Comment by earlephilhower** [comment]
Nope, the 2.0 IDE doesn't allow plug ins (yet).  Maybe in the future it will, but for now you're stuck on 1.8 if you need this.

**Comment by okyeron** [comment]
Apologies - I found the appropriate Arduino 2.0 github thread soon after writing this. 
Bummer :(

**Comment by earlephilhower** [comment]
Please see the [arduino-littlefs-plugin](https://github.com/earlephilhower/arduino-littlefs-upload) for use under IDE 2.2.1 or later
