### ISSUE TITLE
Uploading data files and code together

### ISSUE THREAD

**Issue by OnatBulut** [earlephilhower/arduino-pico-littlefs-plugin#7]
Hello, is the uf2 file containing the data saved somewhere after I use the plugin? If yes, where is it located and can I use drag and drop to upload them together with my code?

Maybe even better, would it be possible to combine the both uf2 files to have a single file containing both the data and the code?

It would be very helpful when programming multiple controllers

**Comment by earlephilhower** [comment]
The UF2 is stored in temporary build directory, where the actual app .bin and .uf2 are created.

The UF2 uploader from Microsoft does not support uploading multiple images, or non-sequential data, so you generally can't combine the 2 files.

For a production-line type operation, you can script `picoprobe` or other tools to upload one after the other relatively simply.  I think that would be your best bet.  Good luck!
