### ISSUE TITLE
doens't work for Arduino 2.xxx

### ISSUE THREAD

**Issue by rolandblok** [earlephilhower/arduino-pico-littlefs-plugin#9]
Hi,
Unfortunately doesn't work in Arduino IDE 2.

**Comment by earlephilhower** [comment]
See https://github.com/arduino/arduino-ide/issues/58

**Comment by earlephilhower** [comment]
Please see the [arduino-littlefs-plugin](https://github.com/earlephilhower/arduino-littlefs-upload) for use under IDE 2.2.1 or later
